initial format parser
sshine/hs-jq pull request #38
Opened 2019-10-27 12:06 UTC by Kaptch

#18 
Extended `Expr` with `Format` constructor.
Extended parser with format expression.

2019-10-28 03:40 UTC, sshine requested changes
Excellent.

Could you add some basic tests of e.g.

```
@base64
@base64 "$$$"
@base64 "\("$$$")"
```

This will reveal one bug.

2019-10-28 16:18 UTC, Kaptch commented
Sure.
I'm going to continue working on this PR on the weekend.

2019-10-28 17:42 UTC, sshine commented
Cool beans.

2019-11-01 19:59 UTC, Kaptch commented
I found the source of the bug, but I'm not sure if the format parser parses strings as intended. Could you please take a look at new test entries?

2019-11-02 15:01 UTC, sshine requested changes
Yes, you found it.

Thanks for your work so far.

Here is a summary of the things that I deem missing:

1. Move `space` parsing to *after* the combinator and make use of `lexeme`.
2. Allow for `@format` to contain keywords.
3. Allow for `@format` to begin with number.

If you don't mind providing a single test for 2 and 3, that'd be excellent.

2019-11-02 15:01 UTC, sshine commented on src/Jq/Parser.hs
> +format = Format <$> (chunk "@" >> (field >>= notKeyword)) <*> optional (space >> string)
To avoid littering the high-level combinators with `space` (and risking that we forget them in some places), we have the following conventions:

1. We try to limit the use of `space` in so-called lexeme parsers, simulating lexical analysis.
2. We make each sub-parser responsible for parsing whitespace *after* it rather than before. (Lexeme parsers directly so. Composed parsers indirectly so because they're composed of lexeme parsers and other composed parsers.)

```suggestion
format = Format <$> formatString <*> optional string
  where
    formatString = lexeme $ chunk "@" >> (field >>= notKeyword)
```

We can export `formatString` to the top-level if we need to, but otherwise it serves as our low-level lexeme parser that parses whitespace *after* itself.

---

Incidentally, I wondered if format prefixes, `@foo` are allowed to have keywords in them:

```
$ jq -n '@def "123"'
"123"
```

```suggestion
format = Format <$> formatString <*> optional string
  where
    formatString = lexeme $ chunk "@" >> field
```

---

Lastly, the regex mentioned in #18 is `"@"[a-zA-Z0-9_]+`, and `field :: Parser Text` matches `[a-zA-Z_][a-zA-Z0-9]*`. For this reason, a valid `@format` that would currently fail is:

```
$ jq -n '@42 "123"'
"123"
```

*(A tangential note: Megaparsec does offer [`Text.Megaparsec.Char.Lexer`](http://hackage.haskell.org/package/megaparsec/docs/Text-Megaparsec-Char-Lexer.html) which provides variants of `lexeme` and `symbol` that are compatible with language-specific comment parsers, but I hand-rolled `lexeme` and `sym` instead, since I cannot see that jq has comments, and it felt quicker. This should get refactored eventually, though.)*

2019-11-02 20:16 UTC, sshine approved these changes
Nice, thanks!

2019-11-02 20:25 UTC, merged